import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Vaibhav",
      email: "anonymousintruder17@gmail.com",
      password: bcrypt.hashSync("Strength1@", 8),
      isAdmin: true,
    },
    {
      name: "Mishra",
      email: "vmishra175@gmail.com",
      password: bcrypt.hashSync("Strength1!", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      image: "/images/set2a.jpg",
      name: "Pattu Langa Matching Mom And Daughter Outfit",
      desc: "Mom Langa Blue skirt and blue blouse with front neck work pink dupatta Skirt Hip 36 inches have rope Height 43 inches Dupatta 2.5 meters Blouse Chest 35 Height 14 Sleeve height 10 inches Waist 28 Can alter up to 2 -3inches Daughter outfit Skirt with rope Height 26 Waist 25 Top Height 14.5 Chest 26 Can alter upto 1.5 inches Skirt also two inches extra if yu remove stitches can use them Sleeves attached can stitch if yu prefer",
      location: "Chennai",
      color: "Blue with pink",
      canAlter: "Yes",
      size: "Small, medium / 5-7 years",
      timesWorn: "Once",
      qty: 1,
      price: 8699,
      category: "women",
      rating: 4.5,
      numReviews: 10,
    },
    {
      image: "/images/set3a.jpg",
      name: "Sky Blue And Orange Organza Crop Top",
      desc: "Brand new Sky blue floral organza crop top with orange top. Skirt has 2 layers of lining and waist size is 32-34 inch. Blouse size is 34-36 inch. Not wore even once.",
      location: "Chennai",
      color: "Sky Blue and Orange",
      canAlter: "Yes",
      size: "Skirt 32 Blouse 34",
      timesWorn: "Zero",
      qty: 1,
      price: 4299,
      category: "women",
      rating: 4.5,
      numReviews: 10,
    },
    {
      image: "/images/set7a.jpg",
      name: "Georgette Off White Saree With Mirror Blouse",
      desc: "NEVER WORN (NEW) Georgette off white embroidered saree Pink multicolor mirror blouse Blouse size : 32 (extendable upto 38)",
      location: "Chennai",
      color: "Off White",
      canAlter: "Yes",
      size: "32 to 38",
      timesWorn: "Zero",
      qty: 1,
      price: 4699,
      category: "women",
      rating: 4.5,
      numReviews: 10,
    },
    {
      image: "/images/set9a.jpg",
      name: "Fancy Orange Color Saree With Pink Blouse",
      desc: "Fancy Orange Saree with Pink designer blouse",
      location: "Chennai",
      color: "Orange with pink blouse",
      canAlter: "Yes",
      size: "38",
      timesWorn: "Once",
      qty: 1,
      price: 3999,
      category: "women",
      rating: 4.5,
      numReviews: 10,
    },
    {
      image: "/images/set5a.jpg",
      name: "CZ Chandbalis",
      desc: "One gram part wear CZ chandbalis ( screw back ) with South sea pearls and emerald stone.",
      location: "Chennai",
      color: "White and gold",
      canAlter: "No",
      size: "3.5 in",
      timesWorn: "Zero",
      qty: 1,
      price: 3599,
      category: "jewelry",
      rating: 4.5,
      numReviews: 10,
    },
    {
      image: "/images/set8a.jpg",
      name: "Pochampally Pattu Saree",
      desc: "Light weight pure pochampally silk saree. Heavy Work designer blouse. Blouse size -32 Just wore it for couple of hours . Like new.",
      location: "Chennai",
      color: "Multi and light green",
      canAlter: "Yes",
      size: "Saree",
      timesWorn: "Once",
      qty: 1,
      price: 4999,
      category: "women",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};

export default data;
